base:
    build: ./base
    container_name: aws_base
    environment:
        AWS_CONFIG_FILE: /root/.aws/config
        AWS_DEFAULT_PROFILE: default
        AWS_REGION: us-west-2
        DEBUG: 'True'
    volumes:
        - ./_workspace/aws.config:/root/.aws/config
        - ./_workspace/aws.credentials:/root/.aws/credentials

config:
    image: aws_base
    container_name: aws_config
    extends:
        service: base
    command: configure

bash:
    image: aws_base
    container_name: aws_base
    extends:
        service: base
    entrypoint: ''
    command: bash

cli:
    image: aws_base
    container_name: aws_cli
    extends:
        service: base

kinesis:
    build: ./kinesis
    container_name: aws_kinesis
    extends:
        service: base
    working_dir: /go/src/aws-kinesis
    volumes:
        - ./kinesis/src/aws-kinesis/:/go/src/aws-kinesis/
