base:
    build: ./base
    container_name: aws_base
    environment:
        AWS_CONFIG_FILE: /root/.aws/config
        AWS_DEFAULT_PROFILE: default
        DEBUG: 'True'
    volumes:
        - ./_config/aws.config:/root/.aws/config
        - ./_config/aws.credentials:/root/.aws/credentials

config:
    image: aws_base
    container_name: aws_config
    extends:
        service: base
    command: configure

bash:
    image: aws_base
    container_name: aws_base
    extends:
        service: base
    entrypoint: ''
    command: bash

cli:
    image: aws_base
    container_name: aws_cli
    extends:
        service: base
