image:
    build: ./image

config:
    image: aws_image
    container_name: aws_config
    environment:
        AWS_DEFAULT_PROFILE: default
        AWS_CONFIG_FILE: /root/.aws/config
        DEBUG: 'True'
    volumes:
        - _config/aws.config:/tmp/.aws/config
        - _config/aws.credentials:/tmp/.aws/credentials   
    command: configure

term:
    image: aws_image
    container_name: aws_term
    extends:
        service: config
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    entrypoint: /bin/bash
    command: -c "aws --version"
