base:
    build: ./base
    container_name: aws_base
    environment:
        AWS_CONFIG_FILE: /root/.aws/config
    volumes:
        - ./_workspace/aws-config/:/root/.aws/

config:
    image: aws_base
    container_name: aws_config
    extends:
        service: base
    command: configure

bash:
    image: aws_base
    container_name: aws_base
    extends:
        service: base
    entrypoint: ''
    command: bash

cli:
    image: aws_base
    container_name: aws_cli
    extends:
        service: base
    environment:
        AWS_DEFAULT_PROFILE: default
        AWS_REGION: us-west-2

kinesis:
    build: ./kinesis
    container_name: aws_kinesis
    extends:
        service: base
    environment:
        AWS_DEFAULT_PROFILE: default
        AWS_REGION: us-west-2
    working_dir: /go/src/aws-kinesis
    volumes:
        - ./kinesis/src/aws-kinesis/:/go/src/aws-kinesis/
        - ./_workspace/data.tmpl:/tmp/data.tmpl

kinesis-bash:
    build: ./kinesis
    container_name: aws_kinesis
    extends:
        service: base
    environment:
        AWS_DEFAULT_PROFILE: default
        AWS_REGION: us-west-2
        DEBUG: 1
    working_dir: /go/src/aws-kinesis
    entrypoint: ''
    command: bash
    volumes:
        - ./kinesis/src/aws-kinesis/:/go/src/aws-kinesis/
        - ./_workspace/data.tmpl:/tmp/data.tmpl
